### ISSUE TITLE
Lag when sending commands for switch/number/select

### ISSUE THREAD

**Issue by alexdelprete** [alexdelprete/HA-NeoPool-MQTT#3]
(cross-posted from tasmota repo [discussion](https://github.com/arendst/Tasmota/discussions/19811#discussioncomment-7414338))

@curzon01 I found a major problem for the MQTT switch/number/select entities (and possibly, all modifiable/actionable MQTT entities, well described in HA documentation:

![image](https://github.com/arendst/Tasmota/assets/7027842/67ec09ae-ac8c-489f-aa2d-606695847ddc)

This is the configuration of a MQTT Switch:

```yaml
  switch:
    - unique_id: "neopool_mqtt_light"
      name: "NeoPool MQTT Light"
      device_class: switch
      command_topic: "cmnd/SmartPool/NPLight"
      state_topic: "tele/SmartPool/SENSOR"
      retain: true
      optimistic: false
      value_template: >-
        {{ value_json.NeoPool.Light }}
      payload_on: 1
      payload_off: 0
      state_on: 1
      state_off: 0
      availability_topic: "tele/SmartPool/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
```

When you start HA, or reload the config, these entities are reinitialized. I'm using `tele/SmartPool/SENSOR` to determine the state of the switch. Problem is that if the SENSOR topic is not retained, all the entities are unavailable until the TelePeriod timer expires and the data is refreshed. So in the readme I'm recommending a configuration with `TelePeriod 10` and `SensorRetain 1`. With this config, when you restart/reload HA the NeoPool entities are immediately available. The only minor issue is that if you change the switch state by clicking it, HA sends the command, but it has to wait another TelePeriod cycle to reflect the state change of the switch.

One solution (cleanest one) is to use `SO4 1` and `state_topic`: `stat/SmartPool/NPLIGHT`, that contains the immediate result of the command. This works, and it's immediate when you click the switch, but it has one major issue I wasn't able to solve: when you restart/reload HA, the `stat/SmartPool/NPLIGHT` topic is not available, since it doesn't have the retain flag (like with the SensorRetain command, that I'm using so on HA restart/reload the entities are immediately available), and I found no Tasmota command to enable retain on the result of a command.

I already tried the Backlog compound command, but unfortunately it doesn't work. I think because value_template is parsed before sending the commands, so we still wait the TelePeriod cycle when activating the switch. :(

The only real solution would be to have stat/SmartPool/%command% retainable. But that is a Tasmota FR because I didn't find a way to do that in the documentation.

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/7a61e6a8-baca-440d-a5a7-3768a723d695)

**Comment by curzon01** [comment]
Sorry, this way the Delay trick is also confusing

An issue is also the retain for commands, this is a no go

I prefere to use "optimistic: true" with "retain false", that's works

```yaml
    - unique_id: "neopool_mqtt_light"
      name: "NeoPool MQTT Light"
      device_class: switch
      command_topic: "cmnd/SmartPool/NPLight"
      state_topic: "tele/SmartPool/SENSOR"
      retain: false
      optimistic: true
      value_template: >-
        {{ value_json.NeoPool.Light }}
      payload_on: "NPLight 1;Delay 25;Teleperiod"
      payload_off: "NPLight 0;Delay 25;Teleperiod"
      state_on: 1
      state_off: 0
      availability_topic: "tele/SmartPool/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
```

**Comment by alexdelprete** [comment]
the retain: true was there because I thought about using cmnd/%command% to get the status immediately, but since it's not a response it wouldn't work because the state would be inconsistent if you changed state using the display or another command. I will revert to retain: false for commands.

I evaluated `optimistic: true`, but it's a workaround really. I don't like it particularly. But if there's no way to set retain flag on stat/%commands% I guess it's a possible solution.

If you use optimistic, there's no need to use Delay. Furthermore, Delay 25 is like using TelePeriod 30, so you click and wait 25-30s for the response. It's tha same issue. :)

There's no good workaround...I'll tell users to simply wait...:)

**Comment by alexdelprete** [comment]
Testing NPLight sensor with these configurations:

```yaml
TelePeriod back to 30s and sensor config:

      state_topic: "stat/SmartPool/NPLight"
      optimistic: false
```

At startup (I reload HA config), since the topic does not exist (no command ever received and not retained), the status of the sensor is `unknown`, and it makes sense.

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/5a01aed5-8b9e-4357-9499-af7e1656f65f)

Then I tested the exact same config, but with optimistic on:

```yaml
TelePeriod back to 30s and sensor config:

      state_topic: "stat/SmartPool/NPLight"
      optimistic: true
```

Now I reload the config and....

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/9447c369-8f30-44a5-9ecc-f7c58d599af3)

Good, it's not unknown, but...

![image](https://github.com/alexdelprete/HA-NeoPool-MQTT/assets/7027842/3b38dbff-b922-4f91-8818-d3f88c0bb463)

The real status is really On. That's why I don't like Optimistic. It's a dirty workaround...

There's no real clean solution, except for stat/%commands% being retained.

Since I prefer state consistency over reaction times of a command, I'll write a note telling the users that when they change a config or click a switch they need to wait `TelePeriod` seconds.

If I open a FR on tasmota for having a command that sets stat/%commands% retain flag, would it be considered?
